package com.pizzaboy.backend.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.util.List;

@DynamoDBTable(tableName = "Order")
@AllArgsConstructor
@NoArgsConstructor
@Data
public class Order {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;
    @DynamoDBAttribute
    private List<String> orderItems;
    @DynamoDBAttribute
    private String userAddress;
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "StatusIndex")
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "EmailIndex")
    private String status;
    @DynamoDBIndexHashKey(globalSecondaryIndexName = "EmailIndex")
    private String userEmail;
    @DynamoDBAttribute
    private long orderAmount;
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "StatusIndex")
    @DynamoDBAutoGeneratedTimestamp
    private long creationTimeStamp;
}
